//
// File generated by /cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/InstallArea/x86_64-slc6-gcc47-opt/bin/../../../../../sw/lcg/app/releases/ROOT/5.34.07a/x86_64-slc6-gcc47-opt/root/bin/rootcint at Thu Feb  5 07:44:57 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME srcdISFrameUser_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "SFrameUser_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void FirstCycle_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_FirstCycle(void *p = 0);
   static void *newArray_FirstCycle(Long_t size, void *p);
   static void delete_FirstCycle(void *p);
   static void deleteArray_FirstCycle(void *p);
   static void destruct_FirstCycle(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::FirstCycle*)
   {
      ::FirstCycle *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::FirstCycle >(0);
      static ::ROOT::TGenericClassInfo 
         instance("FirstCycle", ::FirstCycle::Class_Version(), "./include/FirstCycle.h", 30,
                  typeid(::FirstCycle), DefineBehavior(ptr, ptr),
                  &::FirstCycle::Dictionary, isa_proxy, 4,
                  sizeof(::FirstCycle) );
      instance.SetNew(&new_FirstCycle);
      instance.SetNewArray(&newArray_FirstCycle);
      instance.SetDelete(&delete_FirstCycle);
      instance.SetDeleteArray(&deleteArray_FirstCycle);
      instance.SetDestructor(&destruct_FirstCycle);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::FirstCycle*)
   {
      return GenerateInitInstanceLocal((::FirstCycle*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::FirstCycle*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void SecondCycle_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_SecondCycle(void *p = 0);
   static void *newArray_SecondCycle(Long_t size, void *p);
   static void delete_SecondCycle(void *p);
   static void deleteArray_SecondCycle(void *p);
   static void destruct_SecondCycle(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::SecondCycle*)
   {
      ::SecondCycle *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::SecondCycle >(0);
      static ::ROOT::TGenericClassInfo 
         instance("SecondCycle", ::SecondCycle::Class_Version(), "./include/SecondCycle.h", 29,
                  typeid(::SecondCycle), DefineBehavior(ptr, ptr),
                  &::SecondCycle::Dictionary, isa_proxy, 4,
                  sizeof(::SecondCycle) );
      instance.SetNew(&new_SecondCycle);
      instance.SetNewArray(&newArray_SecondCycle);
      instance.SetDelete(&delete_SecondCycle);
      instance.SetDeleteArray(&deleteArray_SecondCycle);
      instance.SetDestructor(&destruct_SecondCycle);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::SecondCycle*)
   {
      return GenerateInitInstanceLocal((::SecondCycle*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::SecondCycle*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *FirstCycle::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *FirstCycle::Class_Name()
{
   return "FirstCycle";
}

//______________________________________________________________________________
const char *FirstCycle::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::FirstCycle*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int FirstCycle::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::FirstCycle*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void FirstCycle::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::FirstCycle*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *FirstCycle::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::FirstCycle*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *SecondCycle::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *SecondCycle::Class_Name()
{
   return "SecondCycle";
}

//______________________________________________________________________________
const char *SecondCycle::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::SecondCycle*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int SecondCycle::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::SecondCycle*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void SecondCycle::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::SecondCycle*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *SecondCycle::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::SecondCycle*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void FirstCycle::Streamer(TBuffer &R__b)
{
   // Stream an object of class FirstCycle.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(FirstCycle::Class(),this);
   } else {
      R__b.WriteClassBuffer(FirstCycle::Class(),this);
   }
}

//______________________________________________________________________________
void FirstCycle::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class FirstCycle.
      TClass *R__cl = ::FirstCycle::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_recoTreeName", (void*)&m_recoTreeName);
      R__insp.InspectMember("string", (void*)&m_recoTreeName, "m_recoTreeName.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_metaTreeName", (void*)&m_metaTreeName);
      R__insp.InspectMember("string", (void*)&m_metaTreeName, "m_metaTreeName.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_stringVariable", (void*)&m_stringVariable);
      R__insp.InspectMember("string", (void*)&m_stringVariable, "m_stringVariable.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_intVariable", &m_intVariable);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_doubleVariable", &m_doubleVariable);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_boolVariable", &m_boolVariable);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_intVecVariable", (void*)&m_intVecVariable);
      R__insp.InspectMember("vector<int>", (void*)&m_intVecVariable, "m_intVecVariable.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_doubleVecVariable", (void*)&m_doubleVecVariable);
      R__insp.InspectMember("vector<double>", (void*)&m_doubleVecVariable, "m_doubleVecVariable.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_stringVecVariable", (void*)&m_stringVecVariable);
      R__insp.InspectMember("vector<std::string>", (void*)&m_stringVecVariable, "m_stringVecVariable.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_boolVecVariable", (void*)&m_boolVecVariable);
      R__insp.InspectMember("vector<bool>", (void*)&m_boolVecVariable, "m_boolVecVariable.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_El_N", &m_El_N);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_El_p_T", &m_El_p_T);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_El_eta", &m_El_eta);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_El_phi", &m_El_phi);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_El_E", &m_El_E);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_o_example_variable", &m_o_example_variable);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_o_El_p_T", (void*)&m_o_El_p_T);
      R__insp.InspectMember("vector<double>", (void*)&m_o_El_p_T, "m_o_El_p_T.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_o_El", (void*)&m_o_El);
      R__insp.InspectMember("vector<SParticle>", (void*)&m_o_El, "m_o_El.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_electronTree", &m_electronTree);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_meta_El_p_T", &m_meta_El_p_T);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_meta_El_eta", &m_meta_El_eta);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_meta_El_phi", &m_meta_El_phi);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_meta_El_E", &m_meta_El_E);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_allEvents", (void*)&m_allEvents);
      R__insp.InspectMember("SSummedVar<Int_t>", (void*)&m_allEvents, "m_allEvents.", true);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_passedEvents", (void*)&m_passedEvents);
      R__insp.InspectMember("SSummedVar<Int_t>", (void*)&m_passedEvents, "m_passedEvents.", true);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_test", (void*)&m_test);
      R__insp.InspectMember("SSummedVar<std::vector<Int_t> >", (void*)&m_test, "m_test.", true);
      SCycleBase::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_FirstCycle(void *p) {
      return  p ? new(p) ::FirstCycle : new ::FirstCycle;
   }
   static void *newArray_FirstCycle(Long_t nElements, void *p) {
      return p ? new(p) ::FirstCycle[nElements] : new ::FirstCycle[nElements];
   }
   // Wrapper around operator delete
   static void delete_FirstCycle(void *p) {
      delete ((::FirstCycle*)p);
   }
   static void deleteArray_FirstCycle(void *p) {
      delete [] ((::FirstCycle*)p);
   }
   static void destruct_FirstCycle(void *p) {
      typedef ::FirstCycle current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::FirstCycle

//______________________________________________________________________________
void SecondCycle::Streamer(TBuffer &R__b)
{
   // Stream an object of class SecondCycle.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(SecondCycle::Class(),this);
   } else {
      R__b.WriteClassBuffer(SecondCycle::Class(),this);
   }
}

//______________________________________________________________________________
void SecondCycle::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class SecondCycle.
      TClass *R__cl = ::SecondCycle::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_FirstCycleTreeName", (void*)&m_FirstCycleTreeName);
      R__insp.InspectMember("string", (void*)&m_FirstCycleTreeName, "m_FirstCycleTreeName.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_example_variable", &m_example_variable);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_El_p_T", &m_El_p_T);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_El", &m_El);
      SCycleBase::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_SecondCycle(void *p) {
      return  p ? new(p) ::SecondCycle : new ::SecondCycle;
   }
   static void *newArray_SecondCycle(Long_t nElements, void *p) {
      return p ? new(p) ::SecondCycle[nElements] : new ::SecondCycle[nElements];
   }
   // Wrapper around operator delete
   static void delete_SecondCycle(void *p) {
      delete ((::SecondCycle*)p);
   }
   static void deleteArray_SecondCycle(void *p) {
      delete [] ((::SecondCycle*)p);
   }
   static void destruct_SecondCycle(void *p) {
      typedef ::SecondCycle current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::SecondCycle

/********************************************************
* src/SFrameUser_Dict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableSFrameUser_Dict();

extern "C" void G__set_cpp_environmentSFrameUser_Dict() {
  G__cpp_reset_tagtableSFrameUser_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevSFrameUser_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* FirstCycle */
static int G__SFrameUser_Dict_626_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   FirstCycle* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new FirstCycle[n];
     } else {
       p = new((void*) gvp) FirstCycle[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new FirstCycle;
     } else {
       p = new((void*) gvp) FirstCycle;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCycle));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameUser_Dict_626_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) FirstCycle::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameUser_Dict_626_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) FirstCycle::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameUser_Dict_626_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) FirstCycle::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameUser_Dict_626_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      FirstCycle::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameUser_Dict_626_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FirstCycle*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameUser_Dict_626_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) FirstCycle::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameUser_Dict_626_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) FirstCycle::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameUser_Dict_626_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) FirstCycle::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameUser_Dict_626_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) FirstCycle::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef FirstCycle G__TFirstCycle;
static int G__SFrameUser_Dict_626_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (FirstCycle*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((FirstCycle*) (soff+(sizeof(FirstCycle)*i)))->~G__TFirstCycle();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (FirstCycle*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((FirstCycle*) (soff))->~G__TFirstCycle();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* SecondCycle */
static int G__SFrameUser_Dict_636_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SecondCycle* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new SecondCycle[n];
     } else {
       p = new((void*) gvp) SecondCycle[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new SecondCycle;
     } else {
       p = new((void*) gvp) SecondCycle;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__SFrameUser_DictLN_SecondCycle));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameUser_Dict_636_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) SecondCycle::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameUser_Dict_636_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SecondCycle::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameUser_Dict_636_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) SecondCycle::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameUser_Dict_636_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      SecondCycle::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameUser_Dict_636_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SecondCycle*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameUser_Dict_636_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SecondCycle::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameUser_Dict_636_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) SecondCycle::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameUser_Dict_636_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SecondCycle::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameUser_Dict_636_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) SecondCycle::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef SecondCycle G__TSecondCycle;
static int G__SFrameUser_Dict_636_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (SecondCycle*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((SecondCycle*) (soff+(sizeof(SecondCycle)*i)))->~G__TSecondCycle();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (SecondCycle*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((SecondCycle*) (soff))->~G__TSecondCycle();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* FirstCycle */

/* SecondCycle */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncSFrameUser_Dict {
 public:
  G__Sizep2memfuncSFrameUser_Dict(): p(&G__Sizep2memfuncSFrameUser_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncSFrameUser_Dict::*p)();
};

size_t G__get_sizep2memfuncSFrameUser_Dict()
{
  G__Sizep2memfuncSFrameUser_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */
static long G__2vbo_FirstCycle_ISCycleBaseConfig_5(long pobject) {
  FirstCycle *G__Lderived=(FirstCycle*)pobject;
  ISCycleBaseConfig *G__Lbase=G__Lderived;
  return((long)G__Lbase-(long)G__Lderived);
}

static long G__2vbo_FirstCycle_ISCycleBaseHist_6(long pobject) {
  FirstCycle *G__Lderived=(FirstCycle*)pobject;
  ISCycleBaseHist *G__Lbase=G__Lderived;
  return((long)G__Lbase-(long)G__Lderived);
}

static long G__2vbo_FirstCycle_ISCycleBaseNTuple_7(long pobject) {
  FirstCycle *G__Lderived=(FirstCycle*)pobject;
  ISCycleBaseNTuple *G__Lbase=G__Lderived;
  return((long)G__Lbase-(long)G__Lderived);
}

static long G__2vbo_FirstCycle_SCycleBaseBase_8(long pobject) {
  FirstCycle *G__Lderived=(FirstCycle*)pobject;
  SCycleBaseBase *G__Lbase=G__Lderived;
  return((long)G__Lbase-(long)G__Lderived);
}

static long G__2vbo_FirstCycle_ISCycleBaseConfig_9(long pobject) {
  FirstCycle *G__Lderived=(FirstCycle*)pobject;
  ISCycleBaseConfig *G__Lbase=G__Lderived;
  return((long)G__Lbase-(long)G__Lderived);
}

static long G__2vbo_FirstCycle_ISCycleBaseConfig_11(long pobject) {
  FirstCycle *G__Lderived=(FirstCycle*)pobject;
  ISCycleBaseConfig *G__Lbase=G__Lderived;
  return((long)G__Lbase-(long)G__Lderived);
}

static long G__2vbo_FirstCycle_SCycleBaseBase_12(long pobject) {
  FirstCycle *G__Lderived=(FirstCycle*)pobject;
  SCycleBaseBase *G__Lbase=G__Lderived;
  return((long)G__Lbase-(long)G__Lderived);
}

static long G__2vbo_FirstCycle_ISCycleBaseHist_14(long pobject) {
  FirstCycle *G__Lderived=(FirstCycle*)pobject;
  ISCycleBaseHist *G__Lbase=G__Lderived;
  return((long)G__Lbase-(long)G__Lderived);
}

static long G__2vbo_FirstCycle_ISCycleBaseNTuple_15(long pobject) {
  FirstCycle *G__Lderived=(FirstCycle*)pobject;
  ISCycleBaseNTuple *G__Lbase=G__Lderived;
  return((long)G__Lbase-(long)G__Lderived);
}

static long G__2vbo_FirstCycle_SCycleBaseBase_16(long pobject) {
  FirstCycle *G__Lderived=(FirstCycle*)pobject;
  SCycleBaseBase *G__Lbase=G__Lderived;
  return((long)G__Lbase-(long)G__Lderived);
}

static long G__2vbo_FirstCycle_ISCycleBaseConfig_18(long pobject) {
  FirstCycle *G__Lderived=(FirstCycle*)pobject;
  ISCycleBaseConfig *G__Lbase=G__Lderived;
  return((long)G__Lbase-(long)G__Lderived);
}

static long G__2vbo_FirstCycle_ISCycleBaseNTuple_19(long pobject) {
  FirstCycle *G__Lderived=(FirstCycle*)pobject;
  ISCycleBaseNTuple *G__Lbase=G__Lderived;
  return((long)G__Lbase-(long)G__Lderived);
}

static long G__2vbo_FirstCycle_SCycleBaseBase_20(long pobject) {
  FirstCycle *G__Lderived=(FirstCycle*)pobject;
  SCycleBaseBase *G__Lbase=G__Lderived;
  return((long)G__Lbase-(long)G__Lderived);
}

static long G__2vbo_SecondCycle_ISCycleBaseConfig_5(long pobject) {
  SecondCycle *G__Lderived=(SecondCycle*)pobject;
  ISCycleBaseConfig *G__Lbase=G__Lderived;
  return((long)G__Lbase-(long)G__Lderived);
}

static long G__2vbo_SecondCycle_ISCycleBaseHist_6(long pobject) {
  SecondCycle *G__Lderived=(SecondCycle*)pobject;
  ISCycleBaseHist *G__Lbase=G__Lderived;
  return((long)G__Lbase-(long)G__Lderived);
}

static long G__2vbo_SecondCycle_ISCycleBaseNTuple_7(long pobject) {
  SecondCycle *G__Lderived=(SecondCycle*)pobject;
  ISCycleBaseNTuple *G__Lbase=G__Lderived;
  return((long)G__Lbase-(long)G__Lderived);
}

static long G__2vbo_SecondCycle_SCycleBaseBase_8(long pobject) {
  SecondCycle *G__Lderived=(SecondCycle*)pobject;
  SCycleBaseBase *G__Lbase=G__Lderived;
  return((long)G__Lbase-(long)G__Lderived);
}

static long G__2vbo_SecondCycle_ISCycleBaseConfig_9(long pobject) {
  SecondCycle *G__Lderived=(SecondCycle*)pobject;
  ISCycleBaseConfig *G__Lbase=G__Lderived;
  return((long)G__Lbase-(long)G__Lderived);
}

static long G__2vbo_SecondCycle_ISCycleBaseConfig_11(long pobject) {
  SecondCycle *G__Lderived=(SecondCycle*)pobject;
  ISCycleBaseConfig *G__Lbase=G__Lderived;
  return((long)G__Lbase-(long)G__Lderived);
}

static long G__2vbo_SecondCycle_SCycleBaseBase_12(long pobject) {
  SecondCycle *G__Lderived=(SecondCycle*)pobject;
  SCycleBaseBase *G__Lbase=G__Lderived;
  return((long)G__Lbase-(long)G__Lderived);
}

static long G__2vbo_SecondCycle_ISCycleBaseHist_14(long pobject) {
  SecondCycle *G__Lderived=(SecondCycle*)pobject;
  ISCycleBaseHist *G__Lbase=G__Lderived;
  return((long)G__Lbase-(long)G__Lderived);
}

static long G__2vbo_SecondCycle_ISCycleBaseNTuple_15(long pobject) {
  SecondCycle *G__Lderived=(SecondCycle*)pobject;
  ISCycleBaseNTuple *G__Lbase=G__Lderived;
  return((long)G__Lbase-(long)G__Lderived);
}

static long G__2vbo_SecondCycle_SCycleBaseBase_16(long pobject) {
  SecondCycle *G__Lderived=(SecondCycle*)pobject;
  SCycleBaseBase *G__Lbase=G__Lderived;
  return((long)G__Lbase-(long)G__Lderived);
}

static long G__2vbo_SecondCycle_ISCycleBaseConfig_18(long pobject) {
  SecondCycle *G__Lderived=(SecondCycle*)pobject;
  ISCycleBaseConfig *G__Lbase=G__Lderived;
  return((long)G__Lbase-(long)G__Lderived);
}

static long G__2vbo_SecondCycle_ISCycleBaseNTuple_19(long pobject) {
  SecondCycle *G__Lderived=(SecondCycle*)pobject;
  ISCycleBaseNTuple *G__Lbase=G__Lderived;
  return((long)G__Lbase-(long)G__Lderived);
}

static long G__2vbo_SecondCycle_SCycleBaseBase_20(long pobject) {
  SecondCycle *G__Lderived=(SecondCycle*)pobject;
  SCycleBaseBase *G__Lbase=G__Lderived;
  return((long)G__Lbase-(long)G__Lderived);
}


/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceSFrameUser_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCycle))) {
     FirstCycle *G__Lderived;
     G__Lderived=(FirstCycle*)0x1000;
     {
       SCycleBase *G__Lpbase=(SCycleBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_SCycleBase),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       ISCycleBase *G__Lpbase=(ISCycleBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_ISCycleBase),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       SCycleBaseExec *G__Lpbase=(SCycleBaseExec*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_SCycleBaseExec),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TSelector *G__Lpbase=(TSelector*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_TSelector),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_ISCycleBaseConfig),(long)G__2vbo_FirstCycle_ISCycleBaseConfig_5,1,2);
     }
     {
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_ISCycleBaseHist),(long)G__2vbo_FirstCycle_ISCycleBaseHist_6,1,2);
     }
     {
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_ISCycleBaseNTuple),(long)G__2vbo_FirstCycle_ISCycleBaseNTuple_7,1,2);
     }
     {
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_SCycleBaseBase),(long)G__2vbo_FirstCycle_SCycleBaseBase_8,1,2);
     }
     {
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_ISCycleBaseConfig),(long)G__2vbo_FirstCycle_ISCycleBaseConfig_9,1,2);
     }
     {
       SCycleBaseConfig *G__Lpbase=(SCycleBaseConfig*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_SCycleBaseConfig),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_ISCycleBaseConfig),(long)G__2vbo_FirstCycle_ISCycleBaseConfig_11,1,2);
     }
     {
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_SCycleBaseBase),(long)G__2vbo_FirstCycle_SCycleBaseBase_12,1,2);
     }
     {
       SCycleBaseHist *G__Lpbase=(SCycleBaseHist*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_SCycleBaseHist),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_ISCycleBaseHist),(long)G__2vbo_FirstCycle_ISCycleBaseHist_14,1,2);
     }
     {
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_ISCycleBaseNTuple),(long)G__2vbo_FirstCycle_ISCycleBaseNTuple_15,1,2);
     }
     {
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_SCycleBaseBase),(long)G__2vbo_FirstCycle_SCycleBaseBase_16,1,2);
     }
     {
       SCycleBaseNTuple *G__Lpbase=(SCycleBaseNTuple*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_SCycleBaseNTuple),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_ISCycleBaseConfig),(long)G__2vbo_FirstCycle_ISCycleBaseConfig_18,1,2);
     }
     {
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_ISCycleBaseNTuple),(long)G__2vbo_FirstCycle_ISCycleBaseNTuple_19,1,2);
     }
     {
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_SCycleBaseBase),(long)G__2vbo_FirstCycle_SCycleBaseBase_20,1,2);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__SFrameUser_DictLN_SecondCycle))) {
     SecondCycle *G__Lderived;
     G__Lderived=(SecondCycle*)0x1000;
     {
       SCycleBase *G__Lpbase=(SCycleBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_SecondCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_SCycleBase),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       ISCycleBase *G__Lpbase=(ISCycleBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_SecondCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_ISCycleBase),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       SCycleBaseExec *G__Lpbase=(SCycleBaseExec*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_SecondCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_SCycleBaseExec),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TSelector *G__Lpbase=(TSelector*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_SecondCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_TSelector),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_SecondCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_SecondCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_ISCycleBaseConfig),(long)G__2vbo_SecondCycle_ISCycleBaseConfig_5,1,2);
     }
     {
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_SecondCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_ISCycleBaseHist),(long)G__2vbo_SecondCycle_ISCycleBaseHist_6,1,2);
     }
     {
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_SecondCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_ISCycleBaseNTuple),(long)G__2vbo_SecondCycle_ISCycleBaseNTuple_7,1,2);
     }
     {
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_SecondCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_SCycleBaseBase),(long)G__2vbo_SecondCycle_SCycleBaseBase_8,1,2);
     }
     {
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_SecondCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_ISCycleBaseConfig),(long)G__2vbo_SecondCycle_ISCycleBaseConfig_9,1,2);
     }
     {
       SCycleBaseConfig *G__Lpbase=(SCycleBaseConfig*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_SecondCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_SCycleBaseConfig),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_SecondCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_ISCycleBaseConfig),(long)G__2vbo_SecondCycle_ISCycleBaseConfig_11,1,2);
     }
     {
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_SecondCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_SCycleBaseBase),(long)G__2vbo_SecondCycle_SCycleBaseBase_12,1,2);
     }
     {
       SCycleBaseHist *G__Lpbase=(SCycleBaseHist*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_SecondCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_SCycleBaseHist),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_SecondCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_ISCycleBaseHist),(long)G__2vbo_SecondCycle_ISCycleBaseHist_14,1,2);
     }
     {
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_SecondCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_ISCycleBaseNTuple),(long)G__2vbo_SecondCycle_ISCycleBaseNTuple_15,1,2);
     }
     {
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_SecondCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_SCycleBaseBase),(long)G__2vbo_SecondCycle_SCycleBaseBase_16,1,2);
     }
     {
       SCycleBaseNTuple *G__Lpbase=(SCycleBaseNTuple*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_SecondCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_SCycleBaseNTuple),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_SecondCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_ISCycleBaseConfig),(long)G__2vbo_SecondCycle_ISCycleBaseConfig_18,1,2);
     }
     {
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_SecondCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_ISCycleBaseNTuple),(long)G__2vbo_SecondCycle_ISCycleBaseNTuple_19,1,2);
     }
     {
       G__inheritance_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_SecondCycle),G__get_linked_tagnum(&G__SFrameUser_DictLN_SCycleBaseBase),(long)G__2vbo_SecondCycle_SCycleBaseBase_20,1,2);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableSFrameUser_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TTree*>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<SMsgType,std::string>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_maplESMsgTypecOstringcOlesslESMsgTypegRcOallocatorlEpairlEconstsPSMsgTypecOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<SMsgType,string>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_maplESMsgTypecOstringcOlesslESMsgTypegRcOallocatorlEpairlEconstsPSMsgTypecOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<SMsgType,string,less<SMsgType> >",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_maplESMsgTypecOstringcOlesslESMsgTypegRcOallocatorlEpairlEconstsPSMsgTypecOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TBranch*>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlETBranchmUcOallocatorlETBranchmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlETBranchmUcOallocatorlETBranchmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlETBranchmUcOallocatorlETBranchmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlETBranchmUcOallocatorlETBranchmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlETBranchmUcOallocatorlETBranchmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("list<TObject*>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_listlETObjectmUcOallocatorlETObjectmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SGeneratorCut>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlESGeneratorCutcOallocatorlESGeneratorCutgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlESGeneratorCutcOallocatorlESGeneratorCutgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlESGeneratorCutcOallocatorlESGeneratorCutgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlESGeneratorCutcOallocatorlESGeneratorCutgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlESGeneratorCutcOallocatorlESGeneratorCutgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SFile>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlESFilecOallocatorlESFilegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlESFilecOallocatorlESFilegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlESFilecOallocatorlESFilegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlESFilecOallocatorlESFilegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlESFilecOallocatorlESFilegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<STree>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlESTreecOallocatorlESTreegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlESTreecOallocatorlESTreegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlESTreecOallocatorlESTreegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlESTreecOallocatorlESTreegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlESTreecOallocatorlESTreegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<Int_t,std::vector<STree> >",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_maplEintcOvectorlESTreecOallocatorlESTreegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlESTreecOallocatorlESTreegRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<STree,allocator<STree> > >",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_maplEintcOvectorlESTreecOallocatorlESTreegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlESTreecOallocatorlESTreegRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<STree,allocator<STree> >,less<int> >",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_maplEintcOvectorlESTreecOallocatorlESTreegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlESTreecOallocatorlESTreegRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SDataSet>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlESDataSetcOallocatorlESDataSetgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlESDataSetcOallocatorlESDataSetgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlESDataSetcOallocatorlESDataSetgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlESDataSetcOallocatorlESDataSetgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlESDataSetcOallocatorlESDataSetgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<std::string,std::string>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_pairlEstringcOstringgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<string,std::string>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_pairlEstringcOstringgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<std::string,std::string> >",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<string,std::string> >",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<string,string> >",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SInputData>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlESInputDatacOallocatorlESInputDatagRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlESInputDatacOallocatorlESInputDatagRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlESInputDatacOallocatorlESInputDatagRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlESInputDatacOallocatorlESInputDatagRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlESInputDatacOallocatorlESInputDatagRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::string>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SParticle>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlESParticlecOallocatorlESParticlegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlESParticlecOallocatorlESParticlegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlESParticlecOallocatorlESParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlESParticlecOallocatorlESParticlegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlESParticlecOallocatorlESParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("SSummedVar<Int_t>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_SSummedVarlEintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Int_t>",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("SSummedVar<std::vector<Int_t> >",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_SSummedVarlEvectorlEintcOallocatorlEintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("SSummedVar<vector<Int_t> >",117,G__get_linked_tagnum(&G__SFrameUser_DictLN_SSummedVarlEvectorlEintcOallocatorlEintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* FirstCycle */
static void G__setup_memvarFirstCycle(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCycle));
   { FirstCycle *p; p=(FirstCycle*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SFrameUser_DictLN_string),-1,-1,4,"m_recoTreeName=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SFrameUser_DictLN_string),-1,-1,4,"m_metaTreeName=",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCyclecLcLValHistsType),-1,-2,4,"GENERAL=0LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCyclecLcLValHistsType),-1,-2,4,"ELECTRON=1LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCyclecLcLValHistsType),-1,-2,4,"MUON=2LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCyclecLcLValHistsType),-1,-2,4,"JETS=3LL",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SFrameUser_DictLN_string),-1,-1,4,"m_stringVariable=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"m_intVariable=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"m_doubleVariable=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"m_boolVariable=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,4,"m_intVecVariable=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"m_doubleVecVariable=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlEstringcOallocatorlEstringgRsPgR),G__defined_typename("vector<std::string>"),-1,4,"m_stringVecVariable=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlEboolcOallocatorlEboolgRsPgR),G__defined_typename("vector<bool>"),-1,4,"m_boolVecVariable=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"m_El_N=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"m_El_p_T=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"m_El_eta=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"m_El_phi=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"m_El_E=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"m_o_example_variable=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"m_o_El_p_T=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlESParticlecOallocatorlESParticlegRsPgR),G__defined_typename("vector<SParticle>"),-1,4,"m_o_El=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SFrameUser_DictLN_TTree),-1,-1,4,"m_electronTree=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"m_meta_El_p_T=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"m_meta_El_eta=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"m_meta_El_phi=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"m_meta_El_E=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SFrameUser_DictLN_SSummedVarlEintgR),G__defined_typename("SSummedVar<Int_t>"),-1,4,"m_allEvents=",0,"!");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SFrameUser_DictLN_SSummedVarlEintgR),G__defined_typename("SSummedVar<Int_t>"),-1,4,"m_passedEvents=",0,"!");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SFrameUser_DictLN_SSummedVarlEvectorlEintcOallocatorlEintgRsPgRsPgR),G__defined_typename("SSummedVar<std::vector<Int_t> >"),-1,4,"m_test=",0,"!");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SFrameUser_DictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* SecondCycle */
static void G__setup_memvarSecondCycle(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_SecondCycle));
   { SecondCycle *p; p=(SecondCycle*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SFrameUser_DictLN_string),-1,-1,4,"m_FirstCycleTreeName=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"m_example_variable=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"m_El_p_T=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SFrameUser_DictLN_vectorlESParticlecOallocatorlESParticlegRsPgR),G__defined_typename("vector<SParticle>"),-1,4,"m_El=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SFrameUser_DictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarSFrameUser_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncFirstCycle(void) {
   /* FirstCycle */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCycle));
   G__memfunc_setup("FirstCycle",1016,G__SFrameUser_Dict_626_0_1, 105, G__get_linked_tagnum(&G__SFrameUser_DictLN_FirstCycle), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BeginCycle",981,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 32, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("EndCycle",775,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 32, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("BeginInputData",1391,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 32, "u 'SInputData' - 11 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("EndInputData",1185,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 32, "u 'SInputData' - 11 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("BeginMasterInputData",2011,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 32, "u 'SInputData' - 11 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("EndMasterInputData",1805,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 32, "u 'SInputData' - 11 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("BeginInputFile",1397,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 32, "u 'SInputData' - 11 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ExecuteEvent",1237,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 32, 
"u 'SInputData' - 11 - - d - 'Double_t' 0 - weight", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("FillValidationHists",1949,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 2, 1, 4, 0, 
"i 'FirstCycle::ValHistsType' - 0 - - u 'TString' - 11 - status", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__SFrameUser_Dict_626_0_11, 85, G__get_linked_tagnum(&G__SFrameUser_DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&FirstCycle::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__SFrameUser_Dict_626_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&FirstCycle::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__SFrameUser_Dict_626_0_13, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&FirstCycle::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__SFrameUser_Dict_626_0_14, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&FirstCycle::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__SFrameUser_DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__SFrameUser_Dict_626_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__SFrameUser_Dict_626_0_19, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&FirstCycle::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__SFrameUser_Dict_626_0_20, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&FirstCycle::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__SFrameUser_Dict_626_0_21, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&FirstCycle::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__SFrameUser_Dict_626_0_22, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&FirstCycle::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~FirstCycle", 1142, G__SFrameUser_Dict_626_0_23, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncSecondCycle(void) {
   /* SecondCycle */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__SFrameUser_DictLN_SecondCycle));
   G__memfunc_setup("SecondCycle",1100,G__SFrameUser_Dict_636_0_1, 105, G__get_linked_tagnum(&G__SFrameUser_DictLN_SecondCycle), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BeginCycle",981,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 32, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("EndCycle",775,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 32, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("BeginInputFile",1397,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 32, "u 'SInputData' - 11 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("BeginInputData",1391,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 32, "u 'SInputData' - 11 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("EndInputData",1185,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 32, "u 'SInputData' - 11 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ExecuteEvent",1237,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 32, 
"u 'SInputData' - 11 - - d - 'Double_t' 0 - weight", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__SFrameUser_Dict_636_0_8, 85, G__get_linked_tagnum(&G__SFrameUser_DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&SecondCycle::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__SFrameUser_Dict_636_0_9, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SecondCycle::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__SFrameUser_Dict_636_0_10, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&SecondCycle::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__SFrameUser_Dict_636_0_11, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&SecondCycle::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__SFrameUser_DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__SFrameUser_Dict_636_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__SFrameUser_Dict_636_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SecondCycle::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__SFrameUser_Dict_636_0_17, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&SecondCycle::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__SFrameUser_Dict_636_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SecondCycle::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__SFrameUser_Dict_636_0_19, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&SecondCycle::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~SecondCycle", 1226, G__SFrameUser_Dict_636_0_20, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncSFrameUser_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalSFrameUser_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {
}

static void G__cpp_setup_func30() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcSFrameUser_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
  G__cpp_setup_func30();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__SFrameUser_DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_vectorlEboolcOallocatorlEboolgRsPgR = { "vector<bool,allocator<bool> >" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_TSelector = { "TSelector" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_ISCycleBaseConfig = { "ISCycleBaseConfig" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_ISCycleBaseHist = { "ISCycleBaseHist" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_SInputData = { "SInputData" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_ISCycleBaseNTuple = { "ISCycleBaseNTuple" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR = { "vector<TTree*,allocator<TTree*> >" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TTree*,allocator<TTree*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_maplESMsgTypecOstringcOlesslESMsgTypegRcOallocatorlEpairlEconstsPSMsgTypecOstringgRsPgRsPgR = { "map<SMsgType,string,less<SMsgType>,allocator<pair<const SMsgType,string> > >" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_SCycleBaseBase = { "SCycleBaseBase" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_SCycleBaseExec = { "SCycleBaseExec" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_ISCycleBase = { "ISCycleBase" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_SCycleBaseNTuple = { "SCycleBaseNTuple" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_vectorlETBranchmUcOallocatorlETBranchmUgRsPgR = { "vector<TBranch*,allocator<TBranch*> >" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_reverse_iteratorlEvectorlETBranchmUcOallocatorlETBranchmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TBranch*,allocator<TBranch*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_listlETObjectmUcOallocatorlETObjectmUgRsPgR = { "list<TObject*,allocator<TObject*> >" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_SCycleBaseHist = { "SCycleBaseHist" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_vectorlESGeneratorCutcOallocatorlESGeneratorCutgRsPgR = { "vector<SGeneratorCut,allocator<SGeneratorCut> >" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_reverse_iteratorlEvectorlESGeneratorCutcOallocatorlESGeneratorCutgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SGeneratorCut,allocator<SGeneratorCut> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_vectorlESFilecOallocatorlESFilegRsPgR = { "vector<SFile,allocator<SFile> >" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_reverse_iteratorlEvectorlESFilecOallocatorlESFilegRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SFile,allocator<SFile> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_vectorlESTreecOallocatorlESTreegRsPgR = { "vector<STree,allocator<STree> >" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_reverse_iteratorlEvectorlESTreecOallocatorlESTreegRsPgRcLcLiteratorgR = { "reverse_iterator<vector<STree,allocator<STree> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_maplEintcOvectorlESTreecOallocatorlESTreegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlESTreecOallocatorlESTreegRsPgRsPgRsPgRsPgR = { "map<int,vector<STree,allocator<STree> >,less<int>,allocator<pair<const int,vector<STree,allocator<STree> > > > >" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_vectorlESDataSetcOallocatorlESDataSetgRsPgR = { "vector<SDataSet,allocator<SDataSet> >" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_reverse_iteratorlEvectorlESDataSetcOallocatorlESDataSetgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SDataSet,allocator<SDataSet> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_pairlEstringcOstringgR = { "pair<string,string>" , 115 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_vectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgR = { "vector<pair<string,string>,allocator<pair<string,string> > >" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_reverse_iteratorlEvectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<string,string>,allocator<pair<string,string> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_vectorlESInputDatacOallocatorlESInputDatagRsPgR = { "vector<SInputData,allocator<SInputData> >" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_reverse_iteratorlEvectorlESInputDatacOallocatorlESInputDatagRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SInputData,allocator<SInputData> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_SCycleBaseConfig = { "SCycleBaseConfig" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_SCycleBase = { "SCycleBase" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_FirstCycle = { "FirstCycle" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_FirstCyclecLcLValHistsType = { "FirstCycle::ValHistsType" , 101 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_vectorlESParticlecOallocatorlESParticlegRsPgR = { "vector<SParticle,allocator<SParticle> >" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_reverse_iteratorlEvectorlESParticlecOallocatorlESParticlegRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SParticle,allocator<SParticle> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_SSummedVarlEintgR = { "SSummedVar<int>" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_SSummedVarlEvectorlEintcOallocatorlEintgRsPgRsPgR = { "SSummedVar<vector<int,allocator<int> > >" , 99 , -1 };
G__linked_taginfo G__SFrameUser_DictLN_SecondCycle = { "SecondCycle" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableSFrameUser_Dict() {
  G__SFrameUser_DictLN_TClass.tagnum = -1 ;
  G__SFrameUser_DictLN_TBuffer.tagnum = -1 ;
  G__SFrameUser_DictLN_TMemberInspector.tagnum = -1 ;
  G__SFrameUser_DictLN_TObject.tagnum = -1 ;
  G__SFrameUser_DictLN_TString.tagnum = -1 ;
  G__SFrameUser_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__SFrameUser_DictLN_vectorlEboolcOallocatorlEboolgRsPgR.tagnum = -1 ;
  G__SFrameUser_DictLN_string.tagnum = -1 ;
  G__SFrameUser_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__SFrameUser_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SFrameUser_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__SFrameUser_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SFrameUser_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__SFrameUser_DictLN_TTree.tagnum = -1 ;
  G__SFrameUser_DictLN_TSelector.tagnum = -1 ;
  G__SFrameUser_DictLN_ISCycleBaseConfig.tagnum = -1 ;
  G__SFrameUser_DictLN_ISCycleBaseHist.tagnum = -1 ;
  G__SFrameUser_DictLN_SInputData.tagnum = -1 ;
  G__SFrameUser_DictLN_ISCycleBaseNTuple.tagnum = -1 ;
  G__SFrameUser_DictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR.tagnum = -1 ;
  G__SFrameUser_DictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SFrameUser_DictLN_maplESMsgTypecOstringcOlesslESMsgTypegRcOallocatorlEpairlEconstsPSMsgTypecOstringgRsPgRsPgR.tagnum = -1 ;
  G__SFrameUser_DictLN_SCycleBaseBase.tagnum = -1 ;
  G__SFrameUser_DictLN_SCycleBaseExec.tagnum = -1 ;
  G__SFrameUser_DictLN_ISCycleBase.tagnum = -1 ;
  G__SFrameUser_DictLN_SCycleBaseNTuple.tagnum = -1 ;
  G__SFrameUser_DictLN_vectorlETBranchmUcOallocatorlETBranchmUgRsPgR.tagnum = -1 ;
  G__SFrameUser_DictLN_reverse_iteratorlEvectorlETBranchmUcOallocatorlETBranchmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SFrameUser_DictLN_listlETObjectmUcOallocatorlETObjectmUgRsPgR.tagnum = -1 ;
  G__SFrameUser_DictLN_SCycleBaseHist.tagnum = -1 ;
  G__SFrameUser_DictLN_vectorlESGeneratorCutcOallocatorlESGeneratorCutgRsPgR.tagnum = -1 ;
  G__SFrameUser_DictLN_reverse_iteratorlEvectorlESGeneratorCutcOallocatorlESGeneratorCutgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SFrameUser_DictLN_vectorlESFilecOallocatorlESFilegRsPgR.tagnum = -1 ;
  G__SFrameUser_DictLN_reverse_iteratorlEvectorlESFilecOallocatorlESFilegRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SFrameUser_DictLN_vectorlESTreecOallocatorlESTreegRsPgR.tagnum = -1 ;
  G__SFrameUser_DictLN_reverse_iteratorlEvectorlESTreecOallocatorlESTreegRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SFrameUser_DictLN_maplEintcOvectorlESTreecOallocatorlESTreegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlESTreecOallocatorlESTreegRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__SFrameUser_DictLN_vectorlESDataSetcOallocatorlESDataSetgRsPgR.tagnum = -1 ;
  G__SFrameUser_DictLN_reverse_iteratorlEvectorlESDataSetcOallocatorlESDataSetgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SFrameUser_DictLN_pairlEstringcOstringgR.tagnum = -1 ;
  G__SFrameUser_DictLN_vectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgR.tagnum = -1 ;
  G__SFrameUser_DictLN_reverse_iteratorlEvectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SFrameUser_DictLN_vectorlESInputDatacOallocatorlESInputDatagRsPgR.tagnum = -1 ;
  G__SFrameUser_DictLN_reverse_iteratorlEvectorlESInputDatacOallocatorlESInputDatagRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SFrameUser_DictLN_SCycleBaseConfig.tagnum = -1 ;
  G__SFrameUser_DictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__SFrameUser_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SFrameUser_DictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__SFrameUser_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SFrameUser_DictLN_SCycleBase.tagnum = -1 ;
  G__SFrameUser_DictLN_FirstCycle.tagnum = -1 ;
  G__SFrameUser_DictLN_FirstCyclecLcLValHistsType.tagnum = -1 ;
  G__SFrameUser_DictLN_vectorlESParticlecOallocatorlESParticlegRsPgR.tagnum = -1 ;
  G__SFrameUser_DictLN_reverse_iteratorlEvectorlESParticlecOallocatorlESParticlegRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SFrameUser_DictLN_SSummedVarlEintgR.tagnum = -1 ;
  G__SFrameUser_DictLN_SSummedVarlEvectorlEintcOallocatorlEintgRsPgRsPgR.tagnum = -1 ;
  G__SFrameUser_DictLN_SecondCycle.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableSFrameUser_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_TClass);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_TObject);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_TString);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_vectorlEboolcOallocatorlEboolgRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_string);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_TTree);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_TSelector);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_ISCycleBaseConfig);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_ISCycleBaseHist);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_SInputData);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_ISCycleBaseNTuple);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_maplESMsgTypecOstringcOlesslESMsgTypegRcOallocatorlEpairlEconstsPSMsgTypecOstringgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_SCycleBaseBase);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_SCycleBaseExec);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_ISCycleBase);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_SCycleBaseNTuple);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_vectorlETBranchmUcOallocatorlETBranchmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlETBranchmUcOallocatorlETBranchmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_listlETObjectmUcOallocatorlETObjectmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_SCycleBaseHist);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_vectorlESGeneratorCutcOallocatorlESGeneratorCutgRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlESGeneratorCutcOallocatorlESGeneratorCutgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_vectorlESFilecOallocatorlESFilegRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlESFilecOallocatorlESFilegRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_vectorlESTreecOallocatorlESTreegRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlESTreecOallocatorlESTreegRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_maplEintcOvectorlESTreecOallocatorlESTreegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlESTreecOallocatorlESTreegRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_vectorlESDataSetcOallocatorlESDataSetgRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlESDataSetcOallocatorlESDataSetgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_pairlEstringcOstringgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_vectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_vectorlESInputDatacOallocatorlESInputDatagRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlESInputDatacOallocatorlESInputDatagRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_SCycleBaseConfig);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_SCycleBase);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_FirstCycle),sizeof(FirstCycle),-1,291072,(char*)NULL,G__setup_memvarFirstCycle,G__setup_memfuncFirstCycle);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_FirstCyclecLcLValHistsType);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_vectorlESParticlecOallocatorlESParticlegRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_reverse_iteratorlEvectorlESParticlecOallocatorlESParticlegRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_SSummedVarlEintgR);
   G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_SSummedVarlEvectorlEintcOallocatorlEintgRsPgRsPgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__SFrameUser_DictLN_SecondCycle),sizeof(SecondCycle),-1,291072,(char*)NULL,G__setup_memvarSecondCycle,G__setup_memfuncSecondCycle);
}
extern "C" void G__cpp_setupSFrameUser_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupSFrameUser_Dict()");
  G__set_cpp_environmentSFrameUser_Dict();
  G__cpp_setup_tagtableSFrameUser_Dict();

  G__cpp_setup_inheritanceSFrameUser_Dict();

  G__cpp_setup_typetableSFrameUser_Dict();

  G__cpp_setup_memvarSFrameUser_Dict();

  G__cpp_setup_memfuncSFrameUser_Dict();
  G__cpp_setup_globalSFrameUser_Dict();
  G__cpp_setup_funcSFrameUser_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncSFrameUser_Dict();
  return;
}
class G__cpp_setup_initSFrameUser_Dict {
  public:
    G__cpp_setup_initSFrameUser_Dict() { G__add_setup_func("SFrameUser_Dict",(G__incsetup)(&G__cpp_setupSFrameUser_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initSFrameUser_Dict() { G__remove_setup_func("SFrameUser_Dict"); }
};
G__cpp_setup_initSFrameUser_Dict G__cpp_setup_initializerSFrameUser_Dict;

