/********************************************************************
* src/SFrameCintex_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/SFrameCintex_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSFrameCintex_Dict();
extern void G__cpp_setup_inheritanceSFrameCintex_Dict();
extern void G__cpp_setup_typetableSFrameCintex_Dict();
extern void G__cpp_setup_memvarSFrameCintex_Dict();
extern void G__cpp_setup_globalSFrameCintex_Dict();
extern void G__cpp_setup_memfuncSFrameCintex_Dict();
extern void G__cpp_setup_funcSFrameCintex_Dict();
extern void G__set_cpp_environmentSFrameCintex_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SFrameCintex_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SFrameCintex_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SFrameCintex_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SFrameCintex_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
